# Generated by Django 6.0.4 on 2026-04-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_typetransport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(db_column='Aerolinea', max_length=100)),
                ('origin', models.CharField(db_column='Origen', max_length=100)),
                ('destination', models.CharField(db_column='Destino', max_length=100)),
                ('departure_date', models.DateTimeField(db_column='FechaSalida')),
                ('arrival_date', models.DateTimeField(db_column='FechaLlegada')),
                ('active', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Vuelo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nombre', max_length=100)),
                ('city', models.CharField(db_column='Ciudad', max_length=100)),
                ('stars', models.IntegerField(blank=True, db_column='Estrellas', null=True)),
                ('category', models.CharField(blank=True, db_column='Categoria', max_length=50, null=True)),
                ('active', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Hotel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(db_column='Origen', max_length=100)),
                ('destination', models.CharField(db_column='Destino', max_length=100)),
                ('active', models.BooleanField(db_column='Activo', default=True)),
                ('type_transport', models.ForeignKey(db_column='IdTipoTransporte', on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to='catalogos.typetransport')),
            ],
            options={
                'db_table': 'Transporte',
                'ordering': ['id'],
            },
        ),
    ]
