# Generated by Django 6.0.4 on 2026-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Vuelo', 'Flight'), ('Hotel', 'Hotel'), ('Transporte', 'Transportation')], db_column='TipoServicio', max_length=50)),
                ('service_id', models.BigIntegerField(db_column='IdServicio')),
                ('price', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(db_column='FechaInicio')),
                ('end_date', models.DateTimeField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'HistorialPrecio',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['service_type', 'service_id'], name='HistorialPr_TipoSer_2bc201_idx'), models.Index(fields=['service_type', 'service_id', 'end_date'], name='HistorialPr_TipoSer_4832a3_idx')],
            },
        ),
    ]
