# Generated by Django 6.0.4 on 2026-04-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_column='Ciudad', max_length=100)),
                ('country', models.CharField(db_column='Pais', max_length=100)),
                ('code', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True, unique=True)),
                ('active', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Destino',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TouristPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Descripcion', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('active', models.BooleanField(db_column='Activo', default=True)),
                ('created_by', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.PROTECT, related_name='tourist_packages', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(db_column='IdDestino', on_delete=django.db.models.deletion.PROTECT, related_name='tourist_packages', to='packages.destination')),
            ],
            options={
                'db_table': 'PaqueteTuristico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Vuelo', 'Flight'), ('Hotel', 'Hotel'), ('Transporte', 'Transportation')], db_column='TipoServicio', max_length=50)),
                ('service_id', models.BigIntegerField(db_column='IdServicio')),
                ('quantity', models.IntegerField(db_column='Cantidad')),
                ('unit_price', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(db_column='IdPaquete', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='packages.touristpackage')),
            ],
            options={
                'db_table': 'DetallePaquete',
                'ordering': ['id'],
            },
        ),
    ]
