# Generated by Django 6.0.4 on 2026-06-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = []
