# Generated by Django 6.0.4 on 2026-04-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_departments_and_municipalities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('national_id', models.CharField(blank=True, db_column='Cedula', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Direccion', max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Numero', max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('active', models.BooleanField(db_column='Activo', default=True)),
                ('created_by', models.ForeignKey(db_column='IdUsuarioRegistro', on_delete=django.db.models.deletion.PROTECT, related_name='registered_clients', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(db_column='IdMunicipio', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='catalogos.municipality')),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
    ]
