# Generated by Django 6.0.4 on 2026-04-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(blank=True, db_column='IdDepartamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='catalogos.department')),
            ],
            options={
                'db_table': 'Municipio',
                'ordering': ['id'],
            },
        ),
    ]
