# Generated by Django 6.0.4 on 2026-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_seed_departments_and_municipalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('code', models.CharField(db_column='Codigo', max_length=20, unique=True)),
                ('active', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'TipoTransporte',
                'ordering': ['id'],
            },
        ),
    ]
